spring:
  profiles:
    active: 
    - dev

---
spring:
  profiles: dev
  application:
    name: microservice-provider-config-8001

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.syb.springcloud.dao             #mybatis包别名
  mapper-locations: mybatis/mapper/**/*.xml                 #配置mapper文件


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            #配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cdb01
    username: root
    password: root
  application:
    name: microservice-dept

eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-dept-8001
    prefer-ip-address: true         #访问路径可以显示Ip地址

info:
  app.name: syb-microservice
  company.name: www.syb.com
  build.artifactId: $project.artifactId@
  build.version: $project.version$
management:
  security:
    enabled: false
    
    
---


spring:
  profiles: test
  application:
    name: microservice-provider-config-8001

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.syb.springcloud.dao             #mybatis包别名
  mapper-locations: mybatis/mapper/**/*.xml                 #配置mapper文件

#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cdb02
    username: root
    password: root
  application:
    name: microservice-dept

eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-dept-8001
    prefer-ip-address: true         #访问路径可以显示Ip地址

info:
  app.name: syb-microservice
  company.name: www.syb.com
  build.artifactId: @project.artifactId$
  build.version: $project.version$
management:
  security:
    enabled: false